# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 2px
    gaps_out = 4px
    border_size = 2
    layout = dwindle
    col.active_border = rgb(aaaaaa)
    col.inactive_border = rgb(313244)
}

dwindle {
    preserve_split = true
}
# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 0

    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = true
        range = 8
        color = rgba(00000066)
    }
# Use round window corners
  fullscreen_opacity = 1
    blur {
        enabled = true
        size =4
        passes = 3
        noise = 0.02
        brightness = 1.0
        contrast = 1.0
        new_optimizations = true
        xray = false
        popups = true
        special = true
    }
}

misc {
    disable_hyprland_logo = true
}
# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 2, myBezier
    animation = windowsOut, 1, 3, default, popin 80%
    animation = border, 1, 2, default
    animation = borderangle, 1,2, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 2, default
}
