# This file contains the specific workspaces rules
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for more info

workspace = 1, monitor:DP-1, persitent:true
workspace = 2, monitor:DP-1, persitent:true
workspace = 3, monitor:DP-1, persitent:true
workspace = 4, monitor:DP-1, persitent:true
workspace = 5, monitor:HDMI-A-1, persitent:true
workspace = 6, monitor:HDMI-A-1, persitent:true
workspace = 7, monitor:HDMI-A-1, persitent:true
workspace = 8, monitor:HDMI-A-1, persitent:true
