alias l='eza -hla --git --icons=auto --time-style="+%Y-%m-%d %H:%M"'
alias lt='eza -hl --tree --level 2 --icons=auto --time-style="+%Y-%m-%d %H:%M"'
alias mux='tmuxinator'
alias t='tmux'
alias ta='tmux attach'
alias c='clear'
alias reload='source ~/.zshrc'
alias ca='cursor-agent'
alias h='history'
alias n='nvim'
alias lg='lazygit'
alias cat='bat -p'
alias y='yazi'
alias r='reload'
alias @tokoserver='ssh tokoserver'
alias @camelot='ssh camelot'
