# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = GTK_THEME,adw-gtk3-dark
#SDL_VIDEODRIVER='wayland,x11,windows'
env = HYPRCURSOR_SIZE,32
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = PATH,$PATH:$HOME/bin/fol:$HOME/bin
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
env = __NV_PRIME_RENDER_OFFLOAD,1
